### ISSUE TITLE
GF_Latin_African glyphset FAILS 

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Oi#12]
There are series of FAILS related to the GF_Latin_African glyphset (mostly the locl Eng alternate) but I could not find the respective Language tags on the Microsoft spec for all the languages mentioned on the report.

The report is too long to be posted in a comment. 

@EbenSorkin what should I do?

**Comment by EbenSorkin** [comment]
So I think what it is looking for is for you to have "Eng.loclNSM" as a
glyph.

[image: image.png]
The default form ( which is a change) is on the left and the highlighted in
blue one is the one we had been making. The Default is dominant in
Afria and has the larger population of users overall. The one of the right
is used by the Sami people in the north of Europe and is also the minority
version in Africa where it is also used.

I have seen in localization code that this 'Eng.loclNSM' is sometimes also
specified in the localization code beyond this:

*script* latn;

*language* NSM;

*lookup* locl_latn_6 {

*sub* Eng *by* Eng.loclNSM;

} locl_latn_6;


but I need to dig that up because I don't have it in Merriweather yet.


Is that helpful? or are you doing this already and getting the error you
mention?

**Comment by kosbarts** [comment]
@EbenSorkin sorry I should have been more descriptive. 

Yes, I have the alternate Eng (.loclNSM) and I have added locl support for a series of languages that the report indicates.

However there are many languages mentioned in the report that don't correspond to any language tag in the [spec.](https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags)

For example there is no 3 letter language tag for Sokoro (or sok) :
* 🔥 **FAIL** <p>GF_Latin_African glyphset:</p>
<table>
<thead>
<tr>
<th align="left">Language</th>
<th align="left">FAIL messages</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">sok_Latn (Sokoro)</td>
<td align="left">The locl feature did not affect Eng</td>
</tr>
</tbody>
</table>


The list of such languages is quite lengthy on the report. 

Whoever did the research for FontBakery should have added the suggested solution somewhere too.

**Comment by EbenSorkin** [comment]
I think you can ignore that one for now then.

I am ccing Dave, Yan and Denis. I'll need the answer to this too.

**Comment by kosbarts** [comment]
Actually this is my brain just playing games for me since there is no actual issue... 
The loclNSM is used in the first lines to make the change for the Sami languages (KSM; NSM; ISM; SKS; LSM; SSM;)

The rest I put there after the fontbakery report but since they are all referring to African languages the default Eng should be fine, and of course the locl feature does not affect the Eng. 

I guess the problem is that fontbakery probably expects the default Eng to be the Sami one. But the character sets are made so that in SSA Eng is expected to be the African one and Eng.loclNSM to be the Sami preferred one. 

In any case I think I can safely disregard these fails in my case.

**Comment by EbenSorkin** [comment]
I don't agree about fontbakery expecting the Sami one - but otherwise; for
now; yes.

**Comment by kosbarts** [comment]
I second that. That report should be a WARN and not a FAIL.

**Comment by yanone** [comment]
The FAIL is produced by Shaperglot and only passed through to Fontbakery. So we'd have to investigate a solution there.

One problem we're definitely having is that we currently have no way of defining what a font is supposed to contain as default shapes, and what as alternative/locl shapes, which is also why the discussion about defining unencoded variants into the glyphsets is stalling. Is a font primarily an African or a European Latin? Is a font primarily Russian or Bulgarian? If both ways are/should be possible within Google Fonts, checks in Fontbakery and Shaperglot need to be flexible enough to react to that. Currently they aren't, so it's possible that they're checking the inverse of what they're supposed to check, which is bound to cause lots of confusion.

I'm lacking knowledge about the languages. My current understanding is that the historically dominating conduct overall is that the default shape of the `Eng` is this, which is also required by Sami:
![Bildschirmfoto 2024-05-15 um 11 10 58](https://github.com/kosbarts/Oi/assets/175386/270e4b2d-f865-4c6d-85f4-7d477a21a97e)
whereas African languages expect this shape:
![Bildschirmfoto 2024-05-15 um 11 11 15](https://github.com/kosbarts/Oi/assets/175386/897ac43d-9f39-4afa-81f3-741588d9e1b7)

Is this correct? In that case it looks like either Oi or Shaperglot is set up the wrong way around and any `locl` variant checks by Shaperglot are bound to fail. This is not a call to action in any way, I'm just trying to unwrap our problem.

@simoncozens: Which way does the Shaperglot check expect?

I'm sure we can take it as a given that languages without a OT code shouldn't produce a FAIL, but let's talk about the above chicken/egg problem first.

**Comment by yanone** [comment]
Don't do anything for now. Let's have a conversation with @simoncozens and also @moyogo first.

We need to answer whether the tooling maybe should be able to react to different sets of defaults and alternatives. This implicates not just Shaperglot, but also the glyphset definitions, as the glyph alternatives there must then also be inverted.

This is not my decision to make, but personally I think it's a good idea to the have the African Eng as default for fonts that are primarily targeting African Latin (even though Oi isn't that, it appears), because it would improve African Latin rendering in situations where languages aren't explicitly set in the application. What does everyone think about that?

So even though Oi appears to not necessarily need the African Eng as the default, let's have that conversation please because it definitely affects other fonts and we’ll keep running into this issue.
